spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bqtl_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:3116}
spring.web.resources.static-locations=file:uploads/
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mySuperSecretKeyForJWTAuthentication123456
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

razorpay.key.id=rzp_test_SqheQ5QiB8TylZ
razorpay.key.secret=DKhTauIPFdm3Jod8qb9UJ68e

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=nareshroyal1154@gmail.com
spring.mail.password=ojfw vpry rinb ytcu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080